# Generated by Django 5.0.2 on 2024-02-29 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
        ('publication', '0003_alter_publication_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='publication_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='publication.publication'),
        ),
    ]
