# Generated by Django 5.0.2 on 2024-03-03 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_customuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
