# Generated by Django 5.0.2 on 2024-02-27 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='image',
            field=models.FileField(upload_to='images/publications/'),
        ),
    ]
