# Generated by Django 5.0.2 on 2024-02-28 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0002_alter_publication_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='image',
            field=models.FileField(upload_to='publications/'),
        ),
    ]
